apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-staging
  namespace: mercurion-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: standard-rwo
