apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercurion-web-node
  namespace: mercurion-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mercurion-web-node
  template:
    metadata:
      labels:
        app: mercurion-web-node
    spec:
      containers:
        - name: web-node
          image: europe-west8-docker.pkg.dev/mercurion-481213/mercurion/mercurion-web-node:1.0-beta-1c8
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8098

          # 1) tutte le env (segrete e non) arrivano dai Secret
          envFrom:
            - secretRef:
                name: mercurion-web-node-env   # creato da .env.mercurion-web-node.beta
            - secretRef:
                name: mercurion-jwt-b64        # contenente le 4 chiavi RSA *_B64

          # 2) override/minime env specifiche di runtime
          env:
            - name: APP_ENV
              value: "staging"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8098"
            - name: HOST
              value: "0.0.0.0"
          
          command: ["node", "dist/main.js"]

          startupProbe:
            tcpSocket:
              port: 8098
            failureThreshold: 60
            periodSeconds: 2          

          livenessProbe:
            tcpSocket:
              port: 8098
            periodSeconds: 10
            failureThreshold: 3         

          readinessProbe:
            tcpSocket:
              port: 8098
            periodSeconds: 5
            failureThreshold: 3         


---
apiVersion: v1
kind: Service
metadata:
  name: mercurion-web-node
  namespace: mercurion-beta
spec:
  type: ClusterIP
  selector:
    app: mercurion-web-node
  ports:
    - port: 8098
      targetPort: 8098
