---
apiVersion: v1
kind: Service
metadata:
  name: mercurion-pg
  namespace: mercurion-beta
spec:
  type: ClusterIP
  selector:
    app: mercurion-pg
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mercurion-pg
  namespace: mercurion-beta
spec:
  serviceName: mercurion-pg
  replicas: 1
  selector:
    matchLabels:
      app: mercurion-pg
  template:
    metadata:
      labels:
        app: mercurion-pg
    spec:
      containers:
        - name: postgres
          image: europe-west8-docker.pkg.dev/mercurion-483615/mercurion/postgres16-pgvector:1.2026.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: mercurion-pg-credentials
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mercurion-pg-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mercurion-pg-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mercurion-pg-credentials
                  key: POSTGRES_DB                     
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          args:
            - "-c"
            - "shared_buffers=4GB"
            - "-c"
            - "work_mem=128MB"
            - "-c"
            - "maintenance_work_mem=4GB"
            - "-c"
            - "max_parallel_maintenance_workers=2"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            # equivalente di shm_size: "4gb"
            - name: dshm
              mountPath: /dev/shm
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "4"
              memory: "10Gi"

      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 30Gi
