apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sl
  namespace: mercurion-beta
spec:
  # importantissimo per il PVC RWO: niente rolling, sempre Recreate
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: redis-sl
  template:
    metadata:
      labels:
        app: redis-sl
    spec:
      containers:
        - name: redis
          image: redis@sha256:4521b581dbddea6e7d81f8fe95ede93f5648aaa66a9dacd581611bf6fe7527bd
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: REDIS_PASSWORD
          command: ["sh", "-c"]
          args:
            - |
              redis-server \
                --requirepass "$REDIS_PASSWORD" \
                --notify-keyspace-events Exg \
                --save "900 1" \
                --save "300 10" \
                --save "60 10000" \
                --dbfilename dump.rdb \
                --dir /data \
                --maxmemory 256mb \
                --maxmemory-policy volatile-ttl
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'redis-cli -a "$REDIS_PASSWORD" ping | grep PONG'
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'redis-cli -a "$REDIS_PASSWORD" ping | grep PONG'
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sl
  namespace: mercurion-beta
spec:
  type: ClusterIP
  selector:
    app: redis-sl
  ports:
    - port: 6379
      targetPort: 6379
