# Dockerfile.staging

# ====== STAGE 1: build Angular ======
FROM node:22.16.0-alpine AS build
WORKDIR /workspace

ARG APP_VERSION
LABEL org.opencontainers.image.version=$APP_VERSION

RUN test "$(node --version)" = "v22.16.0" && test "$(npm --version)" = "10.9.2"

COPY package.json package-lock.json ./
COPY MercurionWebNg/package.json MercurionWebNg/package.json
COPY MercurionWebNode/package.json MercurionWebNode/package.json
COPY packages/rest-contracts/package.json packages/rest-contracts/package.json
COPY packages/socket-contracts/package.json packages/socket-contracts/package.json
COPY MercurionWebNg/patches ./MercurionWebNg/patches
RUN npm ci --ignore-scripts

COPY packages/rest-contracts packages/rest-contracts
COPY packages/socket-contracts packages/socket-contracts
COPY MercurionWebNg ./MercurionWebNg
RUN npm run postinstall

WORKDIR /workspace/MercurionWebNg
# build in configurazione "staging" (baseHref /)
RUN npm run build -- --configuration=staging

# ====== STAGE 2: Nginx statico ======
FROM nginx:1.27-alpine

ARG APP_VERSION
ENV APP_VERSION=$APP_VERSION
LABEL org.opencontainers.image.version=$APP_VERSION

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

# La SPA vive nella document root
COPY --from=build /workspace/MercurionWebNg/dist/mercurion-web-ng/browser/ ./

# Config dedicata per lo stage "staging"
COPY MercurionWebNg/nginx.mercurion_web_ng.staging.conf /etc/nginx/conf.d/default.conf

EXPOSE 3497
CMD ["nginx", "-g", "daemon off;"]
