# ====== STAGE 1: build Angular ======
FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY ./patches ./patches
RUN npm config set legacy-peer-deps=true
RUN npm ci

COPY angular.json tsconfig*.json ./
COPY src ./src
COPY public ./public
COPY tailwind.config.js ./


# build in configurazione "testing" (usa baseHref /m/)
RUN npm run build -- --configuration testing

# ====== STAGE 2: Nginx statico ======
FROM nginx:1.27-alpine

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

# metto tutta la build dentro /m
RUN mkdir -p m
COPY --from=build /app/dist/mercurion-web-ng/browser/ ./m/

COPY nginx.mercurion_web_ng.testing.conf /etc/nginx/conf.d/default.conf

EXPOSE 3497
CMD ["nginx", "-g", "daemon off;"]
