server {
  listen 3497;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # tutta la SPA vive sotto /m/
  location /m/ {
    try_files $uri $uri/ /m/index.html;
  }

  # opzionale ma utile:
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
