apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-data
  namespace: mercurion-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 70Gi
  storageClassName: standard-rwo
