# Limita la dimensione massima dei messaggi (default = 1MB)
max_payload: 262144   
# 256 KB


# (Opzionale ma consigliato) Aumenta la verbosità sugli errori
# per debuggare meglio eventuali rifiuti dei client.
debug: false
trace: false

# (Opzionale) Limita reconnect spam
write_deadline: "2s"
