apiVersion: v1
kind: Pod
metadata:
  name: meili-restore
  namespace: mercurion-core
spec:
  restartPolicy: Never
  containers:
    - name: restore
      image: alpine:3.20
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: meili-data
          mountPath: /meili_data
  volumes:
    - name: meili-data
      persistentVolumeClaim:
        claimName: meili-data
