apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi        
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch-sl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch-sl
  template:
    metadata:
      labels:
        app: meilisearch-sl
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch@sha256:8cd411ba5d9ec2dfce02e241305208eebacce0fd74a72bece21cadd03dc566ce
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_ENV
              value: "production"
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MEILI_LOG_LEVEL
              value: "info"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: meili-credentials
                  key: MEILI_MASTER_KEY
          volumeMounts:
            - name: meili-data
              mountPath: /meili_data
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
      volumes:
        - name: meili-data
          persistentVolumeClaim:
            claimName: meili-data
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch-sl
spec:
  type: ClusterIP
  selector:
    app: meilisearch-sl
  ports:
    - port: 7700
      targetPort: 7700
