services:
  pg_md:
    image: postgres:16
    container_name: pg_md
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: postgres
      POSTGRES_USER: app
    ports: ["5434:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
      - //c/chembl_36_postgresql/chembl_36/chembl_36_postgresql:/import
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d drugcentral"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  pg_data:
  pgdata_chembl36:
  #C:\chembl_36_postgresql\chembl_36\chembl_36_postgresql