# Dockerfile.test

# 1) Base image
FROM node:22-alpine AS test

# 2) Directory di lavoro
WORKDIR /usr/src/app

# 3) Dipendenze di sistema minime (per build di eventuali moduli nativi / Prisma)
RUN apk add --no-cache \
    bash \
    openssl \
    libc6-compat \
    python3 \
    make \
    g++

# 4) Abilita corepack (per usare pnpm senza installarlo globalmente)
RUN corepack enable

# 5) Copia solo i file di dependency per caching più efficiente
#   Aggiungi qui anche package-lock.json se usi npm, o yarn.lock se yarn
COPY package.json package-lock.json ./

# 6) Installa tutte le dipendenze (dev incluse, servono per i test)
RUN npm install

# 7) Copia il resto del codice sorgente
COPY . .

# 8) Variabile ambiente per i test
ENV NODE_ENV=test

RUN npm run build && \
    mkdir -p dist/config && \
    cp -R src/config/keys dist/config/keys && \
    mkdir -p dist/app_modules/notification && \
    cp -R src/app_modules/notification/email-templates dist/app_modules/notification/email-templates

