# infra/nginx-edge/Dockerfile
FROM nginx:1.27-alpine

# Config di default verrà sovrascritta dalla ConfigMap in k8s,
# ma lasciamo comunque qualcosa di valido
RUN rm /etc/nginx/conf.d/default.conf

# Copia delle landing di errore buildate da MercurionLandingFactory
COPY ./mercurion-errors /usr/share/nginx/html/mercurion-errors
