services:
  mercurion_web_ng_beta:
    build:
      context: ../../../MercurionWebNg
      dockerfile: Dockerfile.staging
      args:
        APP_VERSION: ${APP_NG_VERSION}
    image: ${REGISTRY_IMAGE_NG}:${APP_NG_VERSION}

  mercurion_web_node_beta:
    build:
      context: ../../../MercurionWebNode
      dockerfile: Dockerfile.staging
      args:
        APP_VERSION: ${APP_NODE_VERSION}
    image: ${REGISTRY_IMAGE_NODE}:${APP_NODE_VERSION}
  
  mercurion_tox_21_beta:
    build:
      context: ../../../../MercurionAI/MercurionTox21
      dockerfile: Dockerfile.staging
      args:
        APP_VERSION: ${MT21_APP_VERSION}
    image: ${REGISTRY_IMAGE_MT21}:${MT21_APP_VERSION}
  
  nginx_sl_beta:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        APP_VERSION: ${APP_VERSION}
    image: ${REGISTRY_IMAGE_NGINX}:${NGINX_TAG}


  pg_sl_beta:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: postgres16-pgvector:${PGV_TAG}
    container_name: pg_sl_beta
    
  