import { ConfigModule, ConfigService } from '@nestjs/config'
import { Environment } from './config/config.schema'
import { GraphQLError } from 'graphql'
import { GraphQLModule } from '@nestjs/graphql'
import { MercuriusDriver, MercuriusDriverConfig } from '@nestjs/mercurius'
import { FastifyReply, FastifyRequest } from 'fastify'
import GraphQLJSON from 'graphql-type-json'
import {
    CONTRACT_VERSION_HEADER,
    PUBLIC_CONTRACT_VERSION_METADATA,
    contractVersionDetails,
    contractVersionWarning,
    negotiateContractMajor,
    type ContractVersionSelection
} from '@mercurion/rest-contracts'
import {
    createCorrelationId,
    createGraphQLErrorExtensions,
    graphQLStatusForPresentation,
    presentApplicationError,
    presentGraphQLError
} from './exception-handling/application-error-envelope'
import { applyContractVersionResponseHeaders } from './contracts/contract-versioning-http'

interface MercurionGraphQLContext {
    request: FastifyRequest
    reply: FastifyReply
    contractVersion: ContractVersionSelection
}

export function createContractVersionGraphQLError(
    selection: ContractVersionSelection
): GraphQLError | undefined {
    if (selection.kind !== 'invalid' && selection.kind !== 'unsupported') return undefined

    return new GraphQLError(
        selection.kind === 'invalid'
            ? 'Invalid contract major version'
            : 'Unsupported contract major version',
        { extensions: { code: selection.code, details: contractVersionDetails(selection) } }
    )
}

export function createMercurionGraphQLConfig(config: ConfigService): MercuriusDriverConfig {
    const env = config.getOrThrow<Environment>('App.env')
    const isNotDev = env !== Environment.Development

    return {
            driver: MercuriusDriver,
            // The committed SDL is generated by scripts/graphql-schema.ts.
            // Keeping the runtime schema in memory prevents `nest --watch`
            // from observing its own generated file and restarting forever.
            autoSchemaFile: true,
            sortSchema: true,
            buildSchemaOptions: {
                addNewlineAtEnd: true,
            },
            path: PUBLIC_CONTRACT_VERSION_METADATA.graphql.endpoint,
            graphiql: !isNotDev,

            context: (request: FastifyRequest, reply: FastifyReply) => {
                const selection = negotiateContractMajor(request.headers[CONTRACT_VERSION_HEADER])
                applyContractVersionResponseHeaders(reply)
                const warning = contractVersionWarning(selection)
                if (warning) reply.header('Warning', warning)
                return { request, reply, contractVersion: selection }
            },

            hooks: {
                preExecution: (_schema, _document, context) => {
                    const selection = (context as unknown as MercurionGraphQLContext).contractVersion
                    const error = createContractVersionGraphQLError(selection)
                    if (error) throw error
                }
            },

            resolvers: { JSON: GraphQLJSON },

            errorFormatter: (executionResult, ctx) => {
                const { errors, data } = executionResult

                if (!errors || errors.length === 0) {
                    return {
                        statusCode: ctx.reply.statusCode ?? 200,
                        response: { data },
                    }
                }
                const request = ctx.reply.request as FastifyRequest | undefined
                const headers = request?.headers ?? {}
                const correlationId = createCorrelationId(headers['x-correlation-id'] ?? headers['x-request-id'] ?? request?.id)


                const sanitizedErrors = errors.map((err: GraphQLError) => {
                    const original = err.originalError
                    const envelope = original
                        ? presentApplicationError(original, {
                            correlationId,
                            isProduction: isNotDev
                        })
                        : presentGraphQLError({
                            message: err.message,
                            path: err.path,
                            extensions: err.extensions
                        }, {
                            correlationId,
                            isProduction: isNotDev
                        })

                    ctx.reply.statusCode = graphQLStatusForPresentation(envelope)

                    return {
                        message: envelope.message,
                        path: err.path,
                        extensions: createGraphQLErrorExtensions(envelope),
                    }
                })

                return {
                    statusCode: ctx.reply.statusCode ?? 200,
                    response: {
                        data,
                        errors: sanitizedErrors,
                    },
                }
            },
    }
}

export const MercurionGraphQLModule = GraphQLModule.forRootAsync<MercuriusDriverConfig>({
    driver: MercuriusDriver,
    imports: [ConfigModule],
    inject: [ConfigService],
    useFactory: createMercurionGraphQLConfig,
})
